- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
**Description**
This PR adds issue and pull request (PR) templates to the repository. These templates are designed to streamline the process for reporting bugs, requesting features, and submitting PRs by providing a consistent structure for contributors to follow.
- **Issue Templates:** 
- Bug report template
- Feature request template
- **Pull Request Template:** 
- Standardized format for PRs to ensure all necessary information is included and follows project guidelines.
**Related Issue**
Closes #14 .
**Checklist**
> Feat: issue/pr template

- src/app/.github/workflow/greetings.yml
This PR introduces a new GitHub Actions workflow to automatically greet first-time contributors to our project. The workflow will post welcoming messages on new issues and pull requests from users interacting with the repository for the first time.
Related issues
Closes #18 
**Key features**:
1. Triggers on both pull requests and issues
2. Uses actions/first-interaction@v1 to identify new contributors
3. Custom welcome messages for issues and pull requests
This addition will help create a more welcoming environment for new contributors and encourage community participation.
> Add Automated Greeting Workflow for New Contributors

- package-lock.json
- package.json
- src/app/page.jsx
Added `Lenis` package for smooth scrolling. 
Fixes #8
> feat: Added smooth scrolling using lenis

- prisma/README.md
Added the documentation for Supabase and Prisma.
Fixes #42
> Fix/doc prisma supabase #42

- CodeofConduct.md
Fixes : #35
Created CodeofConduct.md
> Created CodeofConduct.md

- package-lock.json
- package.json
- src/app/layout.jsx
- src/app/notes/page.js
- src/components/ThemeToggle.jsx
- src/context/ThemeProvider.js
- tailwind.config.js
Added light dark theme toggler
Fixes #32
> added theme toggler

- src/app/globals.css
this pr is a change made for hiding the scroll bar
Fixes # (issue)
-added the code in the global.css file
> hidden the scroll bar

- src/components/Navbar.js
Added navbar interaction
Fixes #31 
Screenrecording:
https://github.com/user-attachments/assets/583297c2-2517-425b-92d4-f09b9bcbd8ba
> improved navbar interaction

- src/app/(auth)/sign-in/[[...sign-in]]/page.jsx
- src/app/(auth)/sign-up/[[...sign-up]]/page.jsx
- src/app/page.jsx
- src/middleware.js
Fixed the  404 not found error in login page, and also made '/' route publicly accessible 
Fixes #73 
https://github.com/user-attachments/assets/b8aec10d-bc9a-4ec7-a179-02737532e633
> Fixed: Getting 404 in login page route

- src/app/layout.jsx
- src/components/Navbar.js
Added hamburger navigation in mobile screens.
Fixes #76
> added navbar responsiveness

- .github/workflows/greetings.yml
Adds a github action to create a new "Thank you" comment on newly opened PRs.
fixes #77
> feat: add comment action for new PRs

- package-lock.json
- src/app/page.jsx
Added a go to my diary button where the user gets redirected to /notes on clicking the CTA (if the user is logged in)
******************************************************************************************************************************
Fixes #99
> fixed bottom CTA section

- src/app/daily-quote/page.jsx
Added copy confirmation and loading state
Fixes #150
> Added copy confirmation and loading state

- jsconfig.json
- src/app/contributors/page.jsx
- src/components/Navbar.js
Added the contributors page to the website with sleek ui, matching the theme of the website, integrated footer and navbar in it, fully responsive over all screen sizes, dynamic ui updates as the new contributors are added the repository and best practices while coding.
So i think it deserves a level 3 for my efforts on this page.
Fixes #123 
https://github.com/user-attachments/assets/80c05a5c-ad3d-4a5e-b1f9-42e3bb232691
@TenzDelek Please check this PR and merge this and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.
> Added the contributors page

- src/app/layout.jsx
- src/components/Navbar.js
1. Enhanced Mobile Experience: 
i. Redesigned navigation bar for smaller screens, leveraging a sidebar for better accessibility. 
ii. Implemented icon-based navigation for intuitive user interaction on mobile devices.
2. Corrected API Endpoint: 
i. Fixed the typo in the 'contrubutors' endpoint to 'contributors'.
Hi, @TenzDelek I look forward to your previous request of making some changes to the navigation bar. Somehow I was unable to get the latest code of the repo to my forked repo, due to which I had to delete my repo and fork it again. So my previous raised PR is somehow deleted. I am new to it so I am making these mistakes. 
**Btw here is what i have changed:**
_Old Navgiation …
> Improved Navigation and API Endpoint

- src/app/about/page.jsx
This PR removes the hover for the cards in about page
Fixes #159
> chore: remove hover

- src/components/Footer.js
feat: add dynamic copyright section #185 
Fixes #185
>  feat: add dynamic copyright section #185 

- package-lock.json
- src/app/contributors/page.jsx
Changed  the UI of the Contributors page. 
Fixes # (issue) #202
> Contributors page enhanced to match the UI

- .github/workflows/auto-label.yml
This workflow will automatically apply specific labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests
Fixes #212
> Implement Auto-Labeling Workflow for GitHub 

- src/components/Footer.js
Changed href attribute value to point to faq page
Fixes #222
> fixed faq-link

- CODEOWNERS
> Add CODEOWNERS file to define global code ownership
